import { createFileRoute, Link } from "@tanstack/react-router";
import { CRTScreen } from "@/components/crt/CRTScreen";

export const Route = createFileRoute("/rules")({ component: RulesScreen });

const CARD_TYPES = [
  { tag: "POP", tone: "text-phosphor", title: "POPULATION", desc: "Absurd civilians — filed straight into your cities. Free plays, unlimited per turn. Loses no action budget.", examples: ["3M RETIRED CIRCUS CLOWNS", "12M REALITY-TV FANATICS", "5M FUNDAMENTALIST HOMESTEADERS"] },
  { tag: "WPN", tone: "text-alert", title: "WEAPON", desc: "ICBM / SLBM / Bomber with a warhead yield in megatons. Click the card, then click an enemy city. Direct hit deals yield-in-millions; nearby cities take collateral. Costs 1 launch.", examples: ["MINUTEMAN III + 20MT", "MIRV-Y CHRISTMAS + 100MT", "TU-95 BEAR + 5MT"] },
  { tag: "SECRET", tone: "text-amber", title: "SECRETS", desc: "Dirty tricks: propaganda coups, defectors, ABM shields, super-germs, world opinion, wrench-dropping accidents. One per turn.", examples: ["PROPAGANDA COUP", "TOP SECRET LEAK", "ANTI-BALLISTIC MISSILE", "SUPER-GERM WARFARE"] },
];
const PHASES = [["1. DRAW", "Every surviving nation refills to 6 cards."], ["2. ORDERS", "Queue your round: pop plays, secrets, propaganda, launches."], ["3. RESOLVE", "Motor executes in fixed order: pop → secrets → propaganda → launches."], ["4. FALLOUT", "Irradiated cities bleed 3M per tick over three turns."], ["5. RETALIATE", "Any nation reduced to zero population empties its silos at random targets before dying."]];

function RulesScreen() {
  return <CRTScreen><main className="relative z-10 mx-auto flex min-h-screen max-w-4xl flex-col gap-6 px-6 py-10"><header className="flex items-center justify-between text-xs uppercase tracking-[0.3em] text-phosphor-dim"><Link to="/" className="hover:text-phosphor">&lt; RETURN</Link><span>W.O.P.R. // FIELD MANUAL</span></header><section className="terminal-panel rounded-sm p-8"><h1 className="display text-3xl text-phosphor text-glow">NUCLEAR WAR</h1><p className="mt-2 text-xs uppercase tracking-[0.35em] text-phosphor-dim">A pastiche of the 1965 Malewicki / Flying Buffalo card game, rendered on a WOPR terminal.</p><p className="mt-4 text-sm text-phosphor">Solo simulation vs. three AI superpowers. Grow your population, stockpile warheads, launch, propagandize, declassify secrets. Everybody probably loses.</p></section><section className="terminal-panel rounded-sm p-8"><h2 className="display text-2xl text-glow">CARD TYPES</h2><div className="mt-4 grid gap-4">{CARD_TYPES.map((c) => <div key={c.tag} className="border border-border p-4"><div className="flex items-center gap-2"><span className={`text-xs uppercase tracking-widest ${c.tone}`}>[{c.tag}]</span><span className="display text-lg text-phosphor text-glow">{c.title}</span></div><p className="mt-2 text-sm text-phosphor">{c.desc}</p><p className="mt-2 text-[11px] uppercase tracking-widest text-phosphor-dim">e.g. {c.examples.join(" · ")}</p></div>)}</div></section><section className="terminal-panel rounded-sm p-8"><h2 className="display text-2xl text-glow">TURN PHASES</h2><ol className="mt-4 space-y-2 text-sm text-phosphor">{PHASES.map(([k, v]) => <li key={k}><span className="text-amber text-glow-amber">{k}</span>{" "}<span className="text-phosphor-dim">— {v}</span></li>)}</ol><p className="mt-6 text-xs uppercase tracking-[0.3em] text-alert text-glow-alert">WARNING: when a nation hits zero, it fires Final Retaliation. There are no winners here.</p></section><section className="terminal-panel rounded-sm p-8 text-sm text-phosphor-dim"><h2 className="display text-2xl text-phosphor text-glow">COMBAT NOTES</h2><ul className="mt-4 list-disc space-y-1 pl-6"><li>Bombers are shot down more often than ICBMs (25% vs 5% base intercept).</li><li>DEFCON 1 adds up to 25% intercept on top of base rate.</li><li>10% chance a warhead drifts to the nearest neighbouring city.</li><li>Every ABM shield token cancels one incoming launch, then decays.</li><li>Fallout ticks drain 3M/turn per hit city for up to three turns.</li></ul></section></main></CRTScreen>;
}